local index = {
    { number = 1, route_name = "Oat_FSHDroneNPC" },
    { number = 2, route_name = "Oat_PalusArsenici" },
    { number = 3, route_name = "Oat_SoutheastWell" },
    { number = 4, route_name = "Oat_HollowHarbor" },
    { number = 5, route_name = "Oat_NHopPrint" },
    { number = 6, route_name = "Oat_WHopPrint" },
    { number = 7, route_name = "Oat_FSHEdibleNPC" },
    { number = 8, route_name = "Oat_WeepPool" },
    { number = 9, route_name = "Oat_AetherialFalls" },
    { number = 10, route_name = "Oat_CritDrone" },
    { number = 11, route_name = "Oat_CritEdible" },
    { number = 12, route_name = "Oat_GPBeta" },
    { number = 13, route_name = "Oat_GPAlpha" },
    { number = 14, route_name = "Oat_FSHMutantNPC" },
    { number = 15, route_name = "Oat_CritMutant" } }

local routes = {
[[
{
  "Name": "Oat_FSHDroneNPC",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -86.86493,
      "Y": 19.469818,
      "Z": -250.93463,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -124.3021,
      "Y": 20.11954,
      "Z": -286.25388,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_PalusArsenici",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.18036583,
      "Y": 1.6374114,
      "Z": 29.884962,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.3440776,
      "Y": 3.222236,
      "Z": 60.819504,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.505323,
      "Y": 37.7,
      "Z": 379.0,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -2.2233388,
      "Y": 35.55,
      "Z": 401.0,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 12.0623665,
      "Y": 35.499996,
      "Z": 404.06393,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 21.062,
      "Y": 37.535,
      "Z": 404.56097,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 270.1529,
      "Y": 26.931536,
      "Z": 296.4356,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 279.98605,
      "Y": 25.549995,
      "Z": 287.1076,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 291.2532,
      "Y": 27.364395,
      "Z": 297.63113,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 426.8765,
      "Y": 45.549995,
      "Z": 516.94604,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 407.96985,
      "Y": 45.499992,
      "Z": 536.2802,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 418.10403,
      "Y": 44.831886,
      "Z": 555.2241,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 453.88367,
      "Y": 44.99731,
      "Z": 536.5993,
      "ZoneID": 1237,
      "Radius": 5.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 483.1462,
      "Y": 51.411667,
      "Z": 552.54065,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 526.27094,
      "Y": 53.66671,
      "Z": 597.74176,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_SoutheastWell",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.18036583,
      "Y": 1.6374114,
      "Z": 29.884962,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.3440776,
      "Y": 3.222236,
      "Z": 60.819504,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.505323,
      "Y": 37.7,
      "Z": 377.2086,
      "ZoneID": 1237,
      "Radius": 0.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -2.2233388,
      "Y": 35.55,
      "Z": 399.05292,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 12.0623665,
      "Y": 35.499996,
      "Z": 404.06393,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 20.85498,
      "Y": 37.465508,
      "Z": 404.53918,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 267.83395,
      "Y": 27.55,
      "Z": 298.56433,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 280.33176,
      "Y": 25.549995,
      "Z": 286.5108,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 260.3042,
      "Y": 25.549953,
      "Z": 280.76807,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 242.13652,
      "Y": 24.649073,
      "Z": 298.01645,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 203.70647,
      "Y": 19.47139,
      "Z": 204.68198,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_HollowHarbor",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.18996973,
      "Y": 1.673547,
      "Z": 9.774899,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -30.524311,
      "Y": 1.6374114,
      "Z": -0.18927869,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -61.30047,
      "Y": 3.3357747,
      "Z": -4.5529776,
      "ZoneID": 1237,
      "Radius": 0.5,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -381.2164,
      "Y": 37.97886,
      "Z": -4.568973,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -395.41486,
      "Y": 36.549995,
      "Z": -5.0858326,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -395.525,
      "Y": 38.337852,
      "Z": -20.310875,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -290.07803,
      "Y": 35.927612,
      "Z": -263.8182,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -282.9906,
      "Y": 34.549995,
      "Z": -271.30856,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -284.72467,
      "Y": 34.54999,
      "Z": -291.3752,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -291.06635,
      "Y": 36.306393,
      "Z": -297.46783,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -523.06085,
      "Y": 61.137314,
      "Z": -529.4196,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -527.6982,
      "Y": 59.535225,
      "Z": -534.4114,
      "ZoneID": 1237,
      "Radius": 1.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -502.8581,
      "Y": 58.6,
      "Z": -555.9102,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -563.5004,
      "Y": 69.06067,
      "Z": -647.4596,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_NHopPrint",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.18996973,
      "Y": 1.673547,
      "Z": 9.774899,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -30.524311,
      "Y": 1.6374114,
      "Z": -0.18927869,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -61.953945,
      "Y": 3.4966414,
      "Z": -4.8506637,
      "ZoneID": 1237,
      "Radius": 0.5,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -377.2575,
      "Y": 38.699997,
      "Z": -4.5128436,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -395.79654,
      "Y": 36.549995,
      "Z": -3.5757065,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -395.47278,
      "Y": 38.529953,
      "Z": -20.999811,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -292.9187,
      "Y": 36.699997,
      "Z": -260.7227,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -282.9906,
      "Y": 34.549995,
      "Z": -271.30856,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -262.2127,
      "Y": 34.549953,
      "Z": -279.99042,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -246.92517,
      "Y": 33.195072,
      "Z": -268.9248,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -152.79845,
      "Y": 20.746378,
      "Z": -286.0662,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 918.27014,
      "Y": -58.807934,
      "Z": -337.26886,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_WHopPrint",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.18996973,
      "Y": 1.673547,
      "Z": 9.774899,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -30.524311,
      "Y": 1.6374114,
      "Z": -0.18927869,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -61.953945,
      "Y": 3.4966414,
      "Z": -4.8506637,
      "ZoneID": 1237,
      "Radius": 0.5,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -377.2575,
      "Y": 38.699997,
      "Z": -4.5128436,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -395.79654,
      "Y": 36.549995,
      "Z": -3.5757065,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -395.47278,
      "Y": 38.529953,
      "Z": -20.999811,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -292.9187,
      "Y": 36.699997,
      "Z": -260.7227,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -282.9906,
      "Y": 34.549995,
      "Z": -271.30856,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -262.2127,
      "Y": 34.549953,
      "Z": -279.99042,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -246.92517,
      "Y": 33.195072,
      "Z": -268.9248,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -260.93436,
      "Y": 25.973822,
      "Z": -122.24025,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -257.60974,
      "Y": 24.137041,
      "Z": -99.47855,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -264.24722,
      "Y": 22.417513,
      "Z": -96.118416,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_FSHEdibleNPC",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -459.18552,
      "Y": 37.692913,
      "Z": -67.0865,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "collection point",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": true,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "NormalConditions",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -299.7197,
      "Y": 24.418175,
      "Z": -101.98027,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 3229,
      "WaitForCondition": "NormalConditions",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_WeepPool",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.1713767,
      "Y": 1.6374114,
      "Z": -40.254856,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 4.424992,
      "Y": 3.3168738,
      "Z": -61.221714,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 4.5047,
      "Y": 40.70006,
      "Z": -377.2369,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 5.542412,
      "Y": 36.1206,
      "Z": -364.26135,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 70.5319,
      "Y": 26.042162,
      "Z": -307.08582,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_AetherialFalls",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.1713767,
      "Y": 1.6374114,
      "Z": -40.254856,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 4.6065946,
      "Y": 1.5351574,
      "Z": -52.797794,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 4.4989448,
      "Y": 39.974987,
      "Z": -381.23022,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 4.977034,
      "Y": 38.549995,
      "Z": -395.34424,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 20.894848,
      "Y": 40.47503,
      "Z": -396.14505,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 270.113,
      "Y": 43.049995,
      "Z": -315.23532,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 288.61658,
      "Y": 41.0,
      "Z": -298.12775,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 309.88477,
      "Y": 41.0,
      "Z": -295.82416,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 322.0627,
      "Y": 42.910336,
      "Z": -306.05972,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 405.27966,
      "Y": -56.950012,
      "Z": -375.90213,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 424.48242,
      "Y": -59.000004,
      "Z": -394.47787,
      "ZoneID": 1237,
      "Radius": 1.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 427.35455,
      "Y": -59.0,
      "Z": -403.90872,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 433.95483,
      "Y": -57.015743,
      "Z": -409.73346,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 629.46643,
      "Y": -72.05116,
      "Z": -554.566,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 642.7488,
      "Y": -73.95,
      "Z": -564.2443,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 652.0686,
      "Y": -72.09266,
      "Z": -551.93567,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 866.0717,
      "Y": -55.3,
      "Z": -369.7266,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 918.1897,
      "Y": -58.801697,
      "Z": -337.19186,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_CritDrone",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.1713767,
      "Y": 1.6374114,
      "Z": -40.254856,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 4.479732,
      "Y": 3.5326617,
      "Z": -62.033276,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 4.5047,
      "Y": 40.70006,
      "Z": -377.2369,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 5.542412,
      "Y": 36.1206,
      "Z": -364.26135,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -44.797047,
      "Y": 21.443571,
      "Z": -303.9351,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -124.4039,
      "Y": 20.11964,
      "Z": -286.2701,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_CritEdible",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -29.37812,
      "Y": 1.6374114,
      "Z": -0.08789409,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -56.809,
      "Y": 2.2789521,
      "Z": -4.479818,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -381.1497,
      "Y": 37.994553,
      "Z": -4.5224543,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -365.83487,
      "Y": 35.6,
      "Z": -5.589788,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -299.7197,
      "Y": 24.418175,
      "Z": -101.98027,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_GPBeta",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.103795595,
      "Y": 1.6374114,
      "Z": 28.13439,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.5998373,
      "Y": 2.210833,
      "Z": 56.521038,
      "ZoneID": 1237,
      "Radius": 0.5,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.5678906,
      "Y": 36.883904,
      "Z": 381.61838,
      "ZoneID": 1237,
      "Radius": 0.25,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -4.6146383,
      "Y": 37.412395,
      "Z": 420.6277,
      "ZoneID": 1237,
      "Radius": 0.5,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -104.52234,
      "Y": 52.447014,
      "Z": 731.35016,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -104.72006,
      "Y": 51.0,
      "Z": 739.932,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -121.5239,
      "Y": 54.777584,
      "Z": 740.05133,
      "ZoneID": 1237,
      "Radius": 0.25,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -320.16367,
      "Y": 53.983307,
      "Z": 739.94635,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -328.09955,
      "Y": 50.999996,
      "Z": 738.7892,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -351.90726,
      "Y": 51.04999,
      "Z": 739.8641,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -360.93307,
      "Y": 51.059944,
      "Z": 713.2792,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -357.556,
      "Y": 47.926914,
      "Z": 639.79474,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_GPAlpha",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": -0.103795595,
      "Y": 1.6374114,
      "Z": 28.13439,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.5998373,
      "Y": 2.210833,
      "Z": 56.521038,
      "ZoneID": 1237,
      "Radius": 0.5,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -4.5678906,
      "Y": 36.883904,
      "Z": 381.61838,
      "ZoneID": 1237,
      "Radius": 0.25,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -4.6146383,
      "Y": 37.412395,
      "Z": 420.6277,
      "ZoneID": 1237,
      "Radius": 0.5,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -104.52234,
      "Y": 52.447014,
      "Z": 731.35016,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -104.72006,
      "Y": 51.0,
      "Z": 739.932,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -121.5239,
      "Y": 54.777584,
      "Z": 740.05133,
      "ZoneID": 1237,
      "Radius": 0.25,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -320.16367,
      "Y": 53.983307,
      "Z": 739.94635,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -328.09955,
      "Y": 50.999996,
      "Z": 738.7892,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -352.42392,
      "Y": 50.999985,
      "Z": 745.6433,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -360.3942,
      "Y": 52.85778,
      "Z": 745.5304,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -716.09174,
      "Y": 92.772896,
      "Z": 759.39233,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -729.4822,
      "Y": 91.549995,
      "Z": 759.524,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -729.4648,
      "Y": 93.40194,
      "Z": 743.41675,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -639.51575,
      "Y": 52.150253,
      "Z": 394.40396,
      "ZoneID": 1237,
      "Radius": 0.3,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": -654.6257,
      "Y": 49.232574,
      "Z": 394.32217,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -656.2147,
      "Y": 49.495056,
      "Z": 401.79385,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -681.05054,
      "Y": 56.904575,
      "Z": 377.3085,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -690.8144,
      "Y": 58.129047,
      "Z": 390.43344,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": -688.1027,
      "Y": 57.122334,
      "Z": 398.869,
      "ZoneID": 1237,
      "Radius": 0.1,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_FSHMutantNPC",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": 110.21583,
      "Y": 18.820879,
      "Z": -229.49133,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 114.87686,
      "Y": 19.747303,
      "Z": -196.94461,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "collection point",
      "Movement": "Normal",
      "InteractWithOID": 2014618,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    }
  ]
}
]],
[[
{
  "Name": "Oat_CritMutant",
  "Group": "Cosmoat",
  "Food": 0,
  "Manual": 0,
  "TargetGatherItem": 0,
  "Waypoints": [
    {
      "X": 0.22309124,
      "Y": 1.6374159,
      "Z": -29.69681,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 4.611054,
      "Y": 3.2466457,
      "Z": -60.923244,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 4.501128,
      "Y": 39.960926,
      "Z": -381.28998,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": false,
      "RouteName": ""
    },
    {
      "X": 4.4453726,
      "Y": 36.484398,
      "Z": -361.40356,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 50.268703,
      "Y": 24.017775,
      "Z": -268.353,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 66.53235,
      "Y": 19.334732,
      "Z": -235.11798,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 112.7228,
      "Y": 19.552847,
      "Z": -211.62195,
      "ZoneID": 1237,
      "Radius": 2.0,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    },
    {
      "X": 110.216,
      "Y": 18.821,
      "Z": -229.491,
      "ZoneID": 1237,
      "Radius": 0.2,
      "InteractWithName": "",
      "Movement": "Normal",
      "InteractWithOID": 0,
      "iX": 0.0,
      "iY": 0.0,
      "iZ": 0.0,
      "showInteractions": false,
      "Interaction": "Standard",
      "showWaits": false,
      "WaitTimeMs": 0,
      "WaitForCondition": "None",
      "Pathfind": true,
      "RouteName": ""
    }
  ]
}
]]
}

local index = {
  { number = 1, route_name = "Oat_FSHDroneNPC" },
  { number = 2, route_name = "Oat_PalusArsenici" },
  { number = 3, route_name = "Oat_SoutheastWell" },
  { number = 4, route_name = "Oat_HollowHarbor" },
  { number = 5, route_name = "Oat_NHopPrint" },
  { number = 6, route_name = "Oat_WHopPrint" },
  { number = 7, route_name = "Oat_FSHEdibleNPC" },
  { number = 8, route_name = "Oat_WeepPool" },
  { number = 9, route_name = "Oat_AetherialFalls" },
  { number = 10, route_name = "Oat_CritDrone" },
  { number = 11, route_name = "Oat_CritEdible" },
  { number = 12, route_name = "Oat_GPBeta" },
  { number = 13, route_name = "Oat_GPAlpha" },
  { number = 14, route_name = "Oat_FSHMutantNPC" },
  { number = 15, route_name = "Oat_CritMutant" }
}

return {
  routes = routes,
  index = index,
}
